import './globals.css'
import type { Metadata} from 'next'

export const metadata: Metadata = {
  title: "Healthy food app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen be-black-100 font-poppins">{children}</body>
    </html>
  );
}
