import './globals.css'
import type { Metadata} from 'next'

export const metadata: Metadata = {
  title: "Healthy food app",
  description: "Generated by create next app",
  other: {
    'theme-color': '#0d1117',
    'color-scheme': "dark only",
    // adding img to sharig link
    'twitter:image': '/twitter_img.png',
    'twetter:card': 'summary_large_image',
    'og:url': "https://next-js-web-site-jade.vercel.app",
    'og:image': 'summary_large_image',
    'og:type':'website',

  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-black-100 font-poppins">{children}</body>
    </html>
  );
}
